name: Tests

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout 👀
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: pip install -U pip

      - name: Install test dependencies
        run: pip install -r requirements.txt -r requirements-test.txt

      - name: Run tests
        env:
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        run: pytest -v
